import { Check, X } from 'lucide-react'

const yes = ['You have ideas but struggle to finish them','You want a practical extra income skill','You need structure, not more scattered advice','You can commit focused time for seven days']
const no = ['You want guaranteed income or instant riches','You are unwilling to complete the daily actions','You expect someone else to build everything for you']

export function WhoThisIsFor(){return <section id="audience" className="scroll-mt-24 px-5 py-20"><div className="mx-auto max-w-5xl"><h2 className="text-center font-serif text-3xl font-black sm:text-4xl">Is this guide right for you?</h2><p className="mx-auto mt-4 max-w-2xl text-center text-base leading-relaxed text-muted-foreground sm:text-lg">This system works best for people who are <strong className="text-foreground">ready to move</strong>, not those still collecting information.</p><div className="mt-10 grid gap-6 md:grid-cols-2"><div className="rounded-3xl border-2 border-primary/30 bg-primary/5 p-7"><h3 className="text-xl font-black text-foreground">✓ Yes, if…</h3><ul className="mt-5 flex flex-col gap-4">{yes.map(x=><li key={x} className="flex gap-3 text-sm leading-relaxed sm:text-base"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground"><Check className="size-4"/></span><span className="text-foreground/90">{x}</span></li>)}</ul></div><div className="rounded-3xl border-2 border-destructive/30 bg-destructive/5 p-7"><h3 className="text-xl font-black text-foreground">✗ Not if…</h3><ul className="mt-5 flex flex-col gap-4">{no.map(x=><li key={x} className="flex gap-3 text-sm leading-relaxed sm:text-base"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-destructive text-primary-foreground"><X className="size-4"/></span><span className="text-foreground/90">{x}</span></li>)}</ul></div></div></div></section>}

export function Testimonials(){return null}

export function Comparison(){return <section className="px-5 py-20"><div className="mx-auto max-w-5xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-primary">Why this guide is different</p><h2 className="mt-3 font-serif text-3xl font-black sm:text-4xl">Less learning. More finishing.</h2><p className="mx-auto mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground sm:text-lg">Most products teach you <em>about</em> creating. This one <strong className="text-foreground">walks you through creating</strong>.</p></div><div className="mt-10 overflow-hidden rounded-3xl border-2 border-border shadow-lg"><div className="grid grid-cols-2 bg-secondary p-4 text-sm font-black sm:text-base md:text-lg"><span className="text-muted-foreground">Typical information products</span><span className="text-primary">The 7-Day System</span></div>{[['Hours of theory','One action per day'],['Requires paid AI tools','Works with free ChatGPT'],['Stops at product creation','Includes setup and launch'],['Leaves you deciding what next','Checklists tell you the next move'],['Promises outcomes it cannot control','Promises a clear execution path']].map(([a,b])=><div key={a} className="grid grid-cols-2 border-t border-border p-4 text-xs sm:text-sm md:text-base"><span className="text-muted-foreground">{a}</span><span className="font-bold text-foreground">{b}</span></div>)}</div></div></section>}
