import { Check, X } from 'lucide-react'

const yes = ['You have ideas but struggle to finish them','You want a practical extra income skill','You need structure, not more scattered advice','You can commit focused time for seven days']
const no = ['You want guaranteed income or instant riches','You are unwilling to complete the daily actions','You expect someone else to build everything for you']

export function WhoThisIsFor(){return <section id="audience" className="scroll-mt-24 px-5 py-20"><div className="mx-auto max-w-5xl"><h2 className="text-center font-serif text-3xl font-black sm:text-4xl">Is this guide right for you?</h2><div className="mt-10 grid gap-6 md:grid-cols-2"><div className="rounded-3xl border border-primary/30 bg-primary/5 p-7"><h3 className="text-xl font-black">Yes, if…</h3><ul className="mt-5 flex flex-col gap-4">{yes.map(x=><li key={x} className="flex gap-3 leading-relaxed"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground"><Check className="size-4"/></span>{x}</li>)}</ul></div><div className="rounded-3xl border border-destructive/30 bg-destructive/5 p-7"><h3 className="text-xl font-black">Not if…</h3><ul className="mt-5 flex flex-col gap-4">{no.map(x=><li key={x} className="flex gap-3 leading-relaxed"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-destructive text-primary-foreground"><X className="size-4"/></span>{x}</li>)}</ul></div></div></div></section>}

export function Testimonials(){return <section className="bg-secondary/60 px-5 py-14"><div className="mx-auto max-w-3xl rounded-3xl border border-border bg-background p-8 text-center"><p className="text-sm font-bold uppercase tracking-widest text-primary">An honest note</p><h2 className="mt-3 font-serif text-2xl font-black">This guide is new. We won&apos;t invent testimonials.</h2><p className="mt-4 leading-relaxed text-muted-foreground">Early readers are working through the system now. Their genuine feedback will appear here only after they have used it. Until then, judge the guide by the process, the previews, and whether the daily plan makes sense for you.</p></div></section>}

export function Comparison(){return <section className="px-5 py-20"><div className="mx-auto max-w-5xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-primary">Why this guide is different</p><h2 className="mt-3 font-serif text-3xl font-black sm:text-4xl">Less learning. More finishing.</h2></div><div className="mt-10 overflow-hidden rounded-3xl border border-border"><div className="grid grid-cols-2 bg-secondary p-4 text-sm font-black sm:text-lg"><span>Typical information products</span><span className="text-primary">The 7-Day System</span></div>{[['Hours of theory','One action per day'],['Requires paid AI tools','Works with free ChatGPT'],['Stops at product creation','Includes setup and launch'],['Leaves you deciding what next','Checklists tell you the next move'],['Promises outcomes it cannot control','Promises a clear execution path']].map(([a,b])=><div key={a} className="grid grid-cols-2 border-t border-border p-4 text-sm sm:text-base"><span className="text-muted-foreground">{a}</span><span className="font-bold">{b}</span></div>)}</div></div></section>}
