'use client'

import { Check, ChevronDown, ShieldCheck } from 'lucide-react'
import { CtaButton } from './cta-button'

const stack=[['Stop Overthinking 7-Day Guide','₦4,800'],['Idea Filter + Buyer Worksheet','₦1,500'],['AI Digital Product Prompt Pack','₦1,500'],['First Launch Content Pack','₦1,000'],['First 30 Days After Launch Plan','₦1,000']]
const faqs=[['Can I use the free version of ChatGPT?','Yes. The prompts and workflow work with free ChatGPT. A paid AI plan is not required.'],['What if I cannot complete it in exactly seven consecutive days?','Use the seven days as focused work sessions. If life interrupts, pause and continue with the next day rather than quitting.'],['Do I need business or technical experience?','No. The system is designed for beginners and explains each action in plain language.'],['What kind of digital product can I create?','An ebook, guide, checklist, template, workbook, mini-course outline, or another simple knowledge-based product.'],['Will this guarantee that I make money?','No. Income depends on your offer, audience, execution and market. The guide gives you a process for creating and launching, not an income guarantee.'],['How will I receive the guide?','After a successful purchase through Selar, your digital files are delivered through the checkout platform.'],['Can I use this outside Nigeria?','Yes. The principles work internationally. Selar may show locally available payment options based on your location.'],['Is payment secure?','Checkout is handled by Selar. This page does not collect or store your payment card details.'],['What if I get stuck?','Return to the checklist for the current day, complete the smallest next action, and use the included prompts to work through the block.']]

export function Pricing(){return <section id="pricing" className="scroll-mt-24 bg-primary px-5 py-20 text-primary-foreground"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-primary-foreground/70">Today you get</p><h2 className="mt-3 font-serif text-3xl font-black sm:text-4xl">The complete action bundle</h2></div><div className="mt-10 overflow-hidden rounded-3xl bg-background text-foreground shadow-2xl"><div className="p-7 sm:p-10"><ul className="flex flex-col gap-4">{stack.map(([name,value])=><li key={name} className="flex items-center justify-between gap-4 border-b border-border pb-4"><span className="flex gap-3 font-bold"><Check className="size-5 shrink-0 text-primary"/>{name}</span><span className="shrink-0 text-muted-foreground">{value}</span></li>)}</ul><div className="mt-8 text-center"><p className="text-lg text-muted-foreground">Regular value <span className="line-through">₦9,800</span></p><p className="mt-2 text-sm font-bold uppercase tracking-widest text-primary">Launch price</p><p className="font-serif text-6xl font-black">₦4,800</p><p className="mt-2 font-bold text-primary">You save ₦5,000</p><div className="mt-7"><CtaButton placement="pricing"/></div><p className="mt-4 text-sm text-muted-foreground">Secure checkout on Selar · Digital delivery after payment</p></div></div><div className="bg-accent px-6 py-4 text-center font-bold text-accent-foreground">Launch pricing won&apos;t stay this low forever. No fake countdown—just an honest introductory price.</div></div></div></section>}

export function Bonuses(){return null}

export function Guarantee(){return <section className="px-5 py-16"><div className="mx-auto flex max-w-3xl flex-col items-center rounded-3xl border-2 border-accent bg-accent/10 p-8 text-center sm:p-10"><div className="flex size-16 items-center justify-center rounded-full bg-accent text-accent-foreground"><ShieldCheck className="size-8"/></div><h2 className="mt-5 font-serif text-3xl font-black">The 7-Day Action Guarantee</h2><p className="mt-4 max-w-xl leading-relaxed text-muted-foreground">Complete the daily exercises and follow the action steps. If the system does not give you a clear path from idea to a finished product, contact us within seven days of purchase. This protects action-takers, not unopened downloads.</p></div></section>}

export function FAQ(){return <section id="faq" className="scroll-mt-24 bg-secondary/60 px-5 py-20"><div className="mx-auto max-w-3xl"><h2 className="text-center font-serif text-3xl font-black sm:text-4xl">Questions before you start</h2><div className="mt-10 flex flex-col gap-3">{faqs.map(([q,a])=><details key={q} className="group rounded-2xl border border-border bg-background p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold">{q}<ChevronDown className="size-5 shrink-0 transition group-open:rotate-180"/></summary><p className="mt-4 leading-relaxed text-muted-foreground">{a}</p></details>)}</div></div></section>}

export function Closing(){return <section className="px-5 py-20 text-center"><div className="mx-auto max-w-3xl"><p className="text-sm font-bold uppercase tracking-widest text-primary">Imagine next week</p><h2 className="mt-3 font-serif text-3xl font-black text-balance sm:text-5xl">Seven days from now, your idea could be real, published, and ready to share.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">Not perfect. Not guaranteed to make you rich. But finished—and that completed first product can teach you more than another year of preparing.</p><div className="mt-8"><CtaButton placement="closing"/></div></div></section>}

export function SiteFooter(){return <footer className="border-t border-border px-5 py-10 pb-24 text-center md:pb-10"><p className="font-serif font-black">Hustle Talk With Martin</p><p className="mt-2 text-sm text-muted-foreground">Practical systems for turning knowledge into finished digital products.</p><p className="mt-5 text-xs text-muted-foreground">© {new Date().getFullYear()} Hustle Talk With Martin. No specific income or overnight results are promised.</p></footer>}
