import Image from 'next/image'
import { Check, FileCheck2, Rocket, Sparkles, Target } from 'lucide-react'
import { CtaButton } from './cta-button'

const days = [['1','Choose the right idea','Use the Idea Filter so you stop second-guessing.'],['2','Define the buyer','Get clear on one person and one useful result.'],['3','Build the outline','Turn your knowledge into a simple structure.'],['4','Create with AI','Draft faster without losing your voice.'],['5','Package the product','Polish the content and create a credible offer.'],['6','Set up the sale','Price it, upload it, and prepare launch messages.'],['7','Publish and launch','Put your product in front of real people.']]
const inside = [[Target,'Idea Filter','Choose an idea people can understand and buy.'],[Sparkles,'AI Prompt Pack','Create useful drafts with free ChatGPT.'],[FileCheck2,'Daily Checklists','Know the exact next action every day.'],[Rocket,'Launch Plan','Publish and promote without complicated funnels.']] as const

export function ProductReveal(){return <section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-5xl gap-10 px-5 py-16 md:grid-cols-[.75fr_1.25fr] md:items-center"><Image src="/images/product-cover.png" alt="Stop Overthinking guide" width={460} height={600} className="mx-auto w-60 rounded-xl shadow-2xl"/><div><p className="text-sm font-bold uppercase tracking-widest text-primary-foreground/70">Introducing the execution guide</p><h2 className="mt-3 font-serif text-3xl font-black text-balance sm:text-4xl">One focused week. One finished digital product.</h2><p className="mt-5 max-w-xl text-base leading-relaxed text-primary-foreground/90 sm:text-lg">This is not a motivational ebook. It is a <strong className="text-primary-foreground">practical work-along system</strong> that moves you from <strong>idea to published offer</strong>, one manageable task at a time.</p><div className="mt-8"><CtaButton placement="product_reveal"/></div></div></div></section>}

export function SystemTimeline(){return <section className="px-5 py-20"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-widest text-primary">Your seven-day path</p><h2 className="mt-3 font-serif text-3xl font-black text-balance sm:text-4xl">From scattered idea to published product</h2></div><ol className="relative mt-12 grid gap-5 md:grid-cols-7 md:gap-3 before:absolute before:left-[7%] before:right-[7%] before:top-6 before:hidden before:h-0.5 before:bg-border md:before:block">{days.map(([day,title,text])=><li key={day} className="relative flex gap-4 rounded-2xl border border-border bg-background p-4 md:flex-col md:border-0 md:p-0 md:text-center"><span className="relative z-10 flex size-12 shrink-0 items-center justify-center rounded-full bg-primary font-serif text-lg font-black text-primary-foreground ring-8 ring-background">{day}</span><div><h3 className="text-base font-bold sm:text-base">{title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{text}</p></div></li>)}</ol><div className="mt-14 rounded-3xl bg-secondary p-7 sm:p-10"><h3 className="font-serif text-xl font-black sm:text-2xl">What you&apos;ll have after 7 days</h3><div className="mt-6 grid gap-4 sm:grid-cols-2">{['A validated product idea','A completed digital product','A clear offer and launch message','A live sales page on Selar','The confidence that comes from finally shipping'].map(item=><p key={item} className="flex gap-3 text-sm font-bold sm:text-base"><Check className="size-5 shrink-0 text-primary"/>{item}</p>)}</div></div></div></section>}

export function WhatsInside(){return <section id="inside" className="scroll-mt-24 bg-secondary/60 px-5 py-20"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-widest text-primary">See what&apos;s inside</p><h2 className="mt-3 font-serif text-3xl font-black sm:text-4xl">Tools that turn thinking into action</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{inside.map(([Icon,title,text])=><article key={title} className="rounded-2xl border border-border bg-background p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><Icon className="size-9 text-primary"/><h3 className="mt-5 font-serif text-xl font-black">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{text}</p></article>)}</div><Image src="/images/guide-previews.png" alt="Preview pages showing worksheets, prompts, checklists and frameworks" width={1200} height={750} className="mt-10 w-full rounded-3xl border border-border shadow-xl"/></div></section>}
